version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - revive
    - staticcheck
    - unparam
    - wastedassign
    - whitespace
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - performance
        - style
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - .*_test\.go$
      - .git
      - migrations
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - .*_test\.go$
      - .git
      - migrations
      - third_party$
      - builtin$
      - examples$
